name: ci

on:
  push:
    branches: ['**']

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install
      - name: Build All
        run: yarn build
      - name: Test All
        run: yarn test
